# 3D Array

In [1]:
import numpy as np

arr = np.array([
    [
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]
    ],

    [
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]
    ],

    [
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]
    ]
])

print(arr.shape)

(3, 4, 5)


In [2]:
import numpy as np
print(np.__version__)

2.2.6


In [3]:
# Assignment: 3D Array Indexing & Slicing

# Section A – Access Individual Elements

# Write a statement to extract:

10
24
37
43
54
66
58
49

49

In [4]:
print(arr[0, 0, 0]) #Access Element (0, 0, 0):", 
print(arr[0, 2, 4]) #"Access Element (0, 2, 4):", 
print(arr[1, 1, 2]) #"Access Element (1, 1, 2):",
print(arr[1, 2, 3]) #"Access Element (1, 2, 3):", 
print(arr[2, 0, 4]) #"Access Element (2, 0, 4):",
print(arr[2, 3, 1]) #"Access Element (2, 3, 1):",
print(arr[2, 1, 3]) #"Access Element (2, 1, 3):",
print(arr[1, 3, 4]) #"Access Element (1, 3, 4):", 

10
24
37
43
54
66
58
49


In [5]:
# Section B – Access Complete Rows

# Write a statement to extract:

1.
[15, 16, 17, 18, 19]

2.
[40, 41, 42, 43, 44]

3.
[65, 66, 67, 68, 69]

[65, 66, 67, 68, 69]

In [6]:
print(arr[0,1])
print(arr[1,2])
print(arr[2,3])

[15 16 17 18 19]
[40 41 42 43 44]
[65 66 67 68 69]


In [8]:
# Section C – Access Complete 2D Matrices

# Extract:

# The first matrix
# The second matrix
# The third matrix

In [9]:
print("The first matrix\n\n",arr[0])
print("The second matrix\n\n",arr[1])
print("The third matrix\n\n",arr[2])

The first matrix

 [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
The second matrix

 [[30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
The third matrix

 [[50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]]


In [10]:
# Section D – Column Extraction
1
[10, 15, 20, 25]

2
[32, 37, 42, 47]


3
[54, 59, 64, 69]

[54, 59, 64, 69]

In [11]:
print(arr[0,:,0])
print(arr[1,:,2])
print(arr[2,:,4])

[10 15 20 25]
[32 37 42 47]
[54 59 64 69]


In [ ]:
# # Section E – Slicing

# Extract:

# The first two matrices.
# The last two matrices.
# The first two rows from every matrix.
# The last two rows from every matrix.
# The first three columns from every matrix.
# The last two columns from every matrix.

In [12]:
print(arr[0,0:2,:])
print(arr[0,2:,:])
print(arr[1,0:2,:])
print(arr[1,2:,:])
print(arr[2,0:2,:])
print(arr[2,2:,:])
print(arr[0,0:2,0:2])
print(arr[1,0:2,0:2])
print(arr[2,0:2,0:2])
print(arr[0,:,0:3])
print(arr[1,:,0:3])
print(arr[2,:,0:3])
print(arr[0,:,3:])
print(arr[1,:,3:])
print(arr[2,:,3:])

[[10 11 12 13 14]
 [15 16 17 18 19]]
[[20 21 22 23 24]
 [25 26 27 28 29]]
[[30 31 32 33 34]
 [35 36 37 38 39]]
[[40 41 42 43 44]
 [45 46 47 48 49]]
[[50 51 52 53 54]
 [55 56 57 58 59]]
[[60 61 62 63 64]
 [65 66 67 68 69]]
[[10 11]
 [15 16]]
[[30 31]
 [35 36]]
[[50 51]
 [55 56]]
[[10 11 12]
 [15 16 17]
 [20 21 22]
 [25 26 27]]
[[30 31 32]
 [35 36 37]
 [40 41 42]
 [45 46 47]]
[[50 51 52]
 [55 56 57]
 [60 61 62]
 [65 66 67]]
[[13 14]
 [18 19]
 [23 24]
 [28 29]]
[[33 34]
 [38 39]
 [43 44]
 [48 49]]
[[53 54]
 [58 59]
 [63 64]
 [68 69]]


In [13]:
# Section F – Advanced Slicing

[
 [10, 11, 12],
 [15, 16, 17]
]

[[10, 11, 12], [15, 16, 17]]

In [14]:
print(arr[0,0:2,0:3])

[[10 11 12]
 [15 16 17]]


In [15]:
[
 [42, 43, 44],
 [47, 48, 49]
]

[[42, 43, 44], [47, 48, 49]]

In [16]:
print(arr[1,2:,2:])

[[42 43 44]
 [47 48 49]]


In [17]:
[
 [55, 56],
 [60, 61],
 [65, 66]
]

[[55, 56], [60, 61], [65, 66]]

In [18]:
print(arr[2,1:,0:2])

[[55 56]
 [60 61]
 [65 66]]


In [19]:
[
 [13, 14],
 [18, 19]
]

[[13, 14], [18, 19]]

In [20]:
print(arr[0,0:2,3:])

[[13 14]
 [18 19]]


In [21]:
print(arr[::,::,::])

[[[10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]]


In [23]:
# Section G –  Questions

# Write a single slicing statement to extract:

# Every alternate matrix.
# Every alternate row from all matrices.
# Every alternate column from all matrices.
# The first column from every matrix.
# The last column from every matrix.
# The middle row from every matrix.
# The middle column from every matrix.
# Reverse the order of matrices.
# Reverse the rows inside every matrix.
# Reverse the columns inside every matrix.

# 2D ARRAY

In [24]:
import numpy as np

arr = np.array([
    [10, 11, 12, 13, 14, 15],
    [20, 21, 22, 23, 24, 25],
    [30, 31, 32, 33, 34, 35],
    [40, 41, 42, 43, 44, 45],
    [50, 51, 52, 53, 54, 55],
    [60, 61, 62, 63, 64, 65]
])

print(arr.shape)

(6, 6)


In [26]:
# # 2D Array Indexing & Slicing

# Extract the following using a single indexing/slicing statement
# 1. Every alternate row

# Expected Output:

# [
#  [10,11,12,13,14,15],
#  [30,31,32,33,34,35],
#  [50,51,52,53,54,55]
# ]

In [27]:
print(arr[0::2,0::])

[[10 11 12 13 14 15]
 [30 31 32 33 34 35]
 [50 51 52 53 54 55]]


In [29]:
# # 2. Every alternate column

# Expected Output:

# [
#  [10,12,14],
#  [20,22,24],
#  [30,32,34],
#  [40,42,44],
#  [50,52,54],
#  [60,62,64]
# ]


In [30]:
print(arr[0::,0:5:2])

[[10 12 14]
 [20 22 24]
 [30 32 34]
 [40 42 44]
 [50 52 54]
 [60 62 64]]


In [32]:
# 3. First column

# Expected Output:

# [10,20,30,40,50,60]

In [33]:
print(arr[0:6:1,0:2:4])

[[10]
 [20]
 [30]
 [40]
 [50]
 [60]]


In [35]:
# 4. Last column

# Expected Output:

# [15,25,35,45,55,65]

In [36]:
print(arr[0:6:1,5:6:1])

[[15]
 [25]
 [35]
 [45]
 [55]
 [65]]


In [38]:
# 5. Middle row

# Expected Output:

# [40,41,42,43,44,45]

In [39]:
print(arr[3:4:3,::])

[[40 41 42 43 44 45]]


In [41]:
# 6. Middle column

# Expected Output:

# [13,23,33,43,53,63]

In [42]:
print(arr[::,3:4:3])

[[13]
 [23]
 [33]
 [43]
 [53]
 [63]]


In [43]:
# 7. First three rows

# Expected Output:

# [
#  [10,11,12,13,14,15],
#  [20,21,22,23,24,25],
#  [30,31,32,33,34,35]
# ]


In [44]:
print(arr[0:3:,::])

[[10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]]


In [45]:
# 8. Last three rows

# Expected Output:

# [
#  [40,41,42,43,44,45],
#  [50,51,52,53,54,55],
#  [60,61,62,63,64,65]
# ]


In [46]:
print(arr[3:6:,::])

[[40 41 42 43 44 45]
 [50 51 52 53 54 55]
 [60 61 62 63 64 65]]


In [47]:
# 9. First three columns

# Expected Output:

# [
#  [10,11,12],
#  [20,21,22],
#  [30,31,32],
#  [40,41,42],
#  [50,51,52],
#  [60,61,62]
# ]



In [48]:
print(arr[::,0:3:])

[[10 11 12]
 [20 21 22]
 [30 31 32]
 [40 41 42]
 [50 51 52]
 [60 61 62]]


In [50]:
# 10. Last three columns

# Expected Output:

# [
#  [13,14,15],
#  [23,24,25],
#  [33,34,35],
#  [43,44,45],
#  [53,54,55],
#  [63,64,65]
# ]

In [51]:
print(arr[::,3:6:])

[[13 14 15]
 [23 24 25]
 [33 34 35]
 [43 44 45]
 [53 54 55]
 [63 64 65]]


In [52]:
# 11. Reverse all rows

# Expected Output:

# [
#  [60,61,62,63,64,65],
#  [50,51,52,53,54,55],
#  [40,41,42,43,44,45],
#  [30,31,32,33,34,35],
#  [20,21,22,23,24,25],
#  [10,11,12,13,14,15]
# ]


In [53]:
print(arr[7::-1,::])

[[60 61 62 63 64 65]
 [50 51 52 53 54 55]
 [40 41 42 43 44 45]
 [30 31 32 33 34 35]
 [20 21 22 23 24 25]
 [10 11 12 13 14 15]]


In [54]:
# 12. Reverse all columns

# Expected Output:

# [
#  [15,14,13,12,11,10],
#  [25,24,23,22,21,20],
#  [35,34,33,32,31,30],
#  [45,44,43,42,41,40],
#  [55,54,53,52,51,50],
#  [65,64,63,62,61,60]
# ]

In [55]:
print(arr[::,6::-1])

[[15 14 13 12 11 10]
 [25 24 23 22 21 20]
 [35 34 33 32 31 30]
 [45 44 43 42 41 40]
 [55 54 53 52 51 50]
 [65 64 63 62 61 60]]


In [56]:
# 13. Reverse rows and columns simultaneously

# Expected Output:


# [
#  [65,64,63,62,61,60],
#  [55,54,53,52,51,50],
#  [45,44,43,42,41,40],
#  [35,34,33,32,31,30],
#  [25,24,23,22,21,20],
#  [15,14,13,12,11,10]
# ]

In [57]:
print(arr[6::-1,6::-1])

[[65 64 63 62 61 60]
 [55 54 53 52 51 50]
 [45 44 43 42 41 40]
 [35 34 33 32 31 30]
 [25 24 23 22 21 20]
 [15 14 13 12 11 10]]


# Write a single indexing/slicing statement to extract:


In [58]:

[
 [22,23,24],
 [32,33,34],
 [42,43,44]
]

[[22, 23, 24], [32, 33, 34], [42, 43, 44]]

In [59]:
print(arr[::,::])

[[10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]
 [60 61 62 63 64 65]]


In [60]:
print(arr[1:4:1,2:5:1])

[[22 23 24]
 [32 33 34]
 [42 43 44]]


In [61]:
[
 [11,13,15],
 [31,33,35],
 [51,53,55]
]


[[11, 13, 15], [31, 33, 35], [51, 53, 55]]

In [62]:
print(arr[0:6:2,1:6:2])

[[11 13 15]
 [31 33 35]
 [51 53 55]]


In [63]:
[
 [40,41,42,43,44,45],
 [50,51,52,53,54,55]
]


[[40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]]

In [64]:
print(arr[3:5:1,::])

[[40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [65]:
[
 [14,15],
 [24,25],
 [34,35],
 [44,45],
 [54,55],
 [64,65]
]

[[14, 15], [24, 25], [34, 35], [44, 45], [54, 55], [64, 65]]

In [66]:
print(arr[::,4:6:])

[[14 15]
 [24 25]
 [34 35]
 [44 45]
 [54 55]
 [64 65]]
